spring.datasource.url=jdbc:postgresql://ep-restless-shadow-acdiyrad-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.session.tracking-modes=cookie
logging.level.org.springframework.security=DEBUG
server.port=8082